# Generated by Django 3.1.3 on 2020-11-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('predict_time', models.TimeField(blank=True)),
                ('spent_time', models.TimeField(blank=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
