# Generated by Django 3.1.4 on 2020-12-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyplan', '0004_auto_20201127_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myday',
            name='day_date',
            field=models.DateField(),
        ),
    ]
