# Generated by Django 3.1.7 on 2021-03-26 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_goal_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailytask',
            old_name='day',
            new_name='date',
        ),
    ]
